---
- name: get repo commit ID
  shell: git rev-parse HEAD
  args:
    chdir: "{{ workspace }}"
  register: repo_commit

- name: echo repo commit
  debug:
    msg: "{{ repo_commit.stdout_lines }}"

- name: check if requirements file exists
  stat: 
    path: "{{ workspace }}/requirements.txt"
  register: reqs_present

- name: get python requirements
  shell: "pip3 install --ignore-installed --target ./lib/python3.8/site-packages -r requirements.txt"
  args:
    chdir: "{{ workspace }}/python"
  when: reqs_present.stat.exists == true

- name: build zip archive
  shell: "zip -r {{ version }}.zip python -x *README.md -x *requirements.txt -x '*seronet-devops*'"
  args:
    chdir: "{{ workspace }}"
  register: zip_name

- name: echo zip name
  debug:
    msg: "{{ zip_name }}"

- name: upload zip file to s3
  aws_s3:
    bucket: "{{ procname }}"
    object: "{{ version }}.zip"
    src: "{{ workspace }}/{{ version }}.zip"
    mode: put