---
- name: get repo commit ID
  shell: git rev-parse HEAD
  args:
    chdir: "{{ workspace }}"
  register: repo_commit

- name: echo repo commit
  debug:
    msg: "{{ repo_commit.stdout_lines }}"

- name: install required packages
  pip:
    name:
      - awscli
      - boto3
    state: present

- name: build zip archive
  archive:
    path: "{{ workspace }}/src"
    dest: "{{ workspace }}/{{ version }}.zip"

- name: download file
  aws_s3:
    bucket: "nci-seronet-cbc01-test"
    object: "testing.txt"
    dest: "test.file"
    mode: get

#- name: upload zip file to s3
#  aws_s3:
#    aws_access_key: ''
#    aws_secret_key: ''
#    bucket: "{{ procname }}"
#    object: "{{ version }}.zip"
#    src: "{{ workspace }}/{{ version }}.zip"
#    mode: put