---
- name: get repo url
  shell: git config --get remote.origin.url
  args:
    chdir: "{{ workspace }}/python"
  register: repo_url

- name: get python requirements
  shell: "git checkout {{ commit_id }}"

- name: get repo commit ID
  shell: git rev-parse HEAD
  args:
    chdir: "{{ workspace }}/python"
  register: repo_commit

- name: echo repo url
  debug:
    msg: "{{ repo_url.stdout_lines }}"

- name: echo repo commit
  debug:
    msg: "{{ repo_commit.stdout_lines }}"

- name: check if requirements file exists
  stat: 
    path: "{{ workspace }}/python/requirements.txt"
  register: reqs_present

- name: get python requirements
  shell: "pip3 install --ignore-installed --target ./lib/python3.8/site-packages -r requirements.txt"
  args:
    chdir: "{{ workspace }}/python"
  when: reqs_present.stat.exists == true

- name: write version file
  shell: |
    echo "Current Version:
    Build Number:  {{ build_number }}
    URL: {{ repo_url.stdout_lines }}
    Commit ID: {{ repo_commit.stdout_lines }}" >> {{ workspace }}/python/function_v{{ build_number }}.ver

- name: build zip archive
  shell: "zip -r {{ version }}.zip * -x *README.md -x *requirements.txt -x '*seronet-devops*' -x '*.git*'"
  args:
    chdir: "{{ workspace }}/python"
  register: zip_name

- name: echo zip name
  debug:
    msg: "{{ zip_name }}"

- name: upload zip file to s3
  aws_s3:
    bucket: "{{ procname }}"
    object: "{{ version }}.zip"
    src: "{{ workspace }}/python/{{ version }}.zip"
    mode: put