---
- name: get repo commit ID
  shell: git rev-parse HEAD
  args:
    chdir: "{{ workspace }}"
  register: repo_commit

- name: echo repo commit
  debug:
    msg: "{{ repo_commit.stdout_lines }}"

- name: build zip archive
  archive:
    path: "{{ workspace }}/src/*"
    dest: "{{ workspace }}/{{ version }}.zip"
  register: zip_name

- name: echo zip name
  debug:
    msg: "{{ zip_name }}"

- name: upload zip file to s3
  aws_s3:
    bucket: "{{ procname }}"
    object: "{{ version }}.zip"
    src: "{{ workspace }}/{{ version }}.zip"
    mode: put